version: '3'

services:
  app:
    image: springbootapplicationdemo2:latest
    ports:
      - 8080:8080
    ,

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-mysql-user
      MYSQL_PASSWORD: your-mysql-password
    networks:
      - your-network

networks:
  your-network: